### ISSUE TITLE
关于一些文中的问题

### ISSUE THREAD

**Issue by Love-Camille** [Yu-Fangxu/EACL#2]
感觉是一个很novel的方法，一看作者还是校友，膜拜了，但是文中一些地方弱鸡的我始终没能力理解，比如在equation4那里，请问大佬，这个公式是如何能同时做到u-u，u-a，a-a的效果的呢？

**Comment by Yu-Fangxu** [comment]
校友你好，谢谢关注！
u-u之间的距离有两种，一种是类内距离，一种是类间距离，前者可以通过公式4的分子项缩小u-u之间的相似度使他们更加聚集，后者在分母项使不同类的u更加远离。在每个batch中，我们将anchor包含在其中(公式4中的s)，那么同属于一个类别的u就会和anchor产生交互，使他们更为相似。最后，不同anchor之间的交互是在分母中完成，因为同一类别的anchor只有一个，所以在分子上没有交互。我们也另外设计了equation7，更加显式地减小anchor之间相似度，也作为anchor-anchor交互。

**Comment by Love-Camille** [comment]
原来如此，感谢大佬如此详细的解答！
