### ISSUE TITLE
code problems!!

### ISSUE THREAD

**Issue by version98** [Yu-Fangxu/EACL#3]
There are some bugs in the code, such as the CONFIG in line 61 of data_process.py and tokenizer. Can you provide bug free code?

**Comment by version98** [comment]
In addition, there is also CONFIG [CLS] in data_decess, but there is no definition of CLS in CONFIG

**Comment by Yu-Fangxu** [comment]
Hi,
I update the run.py by removing some additional information line 203. In addition, function build_dataset() is not called by our method, simply run the bash command should make it work.
