### ISSUE TITLE
关于requirements.txt文件的问题

### ISSUE THREAD

**Issue by Dengdan-1999** [Yu-Fangxu/EACL#4]
大佬您好，非常感谢您开放了代码，我看到您的requirement.txt文件里面很多库都是本地安装的，您可以提供一个版本信息吗，因为我在安装这些库的时候老是报版本冲突的错误，感
![屏幕截图 2024-10-23 154909](https://github.com/user-attachments/assets/253e13c7-0331-4092-a53f-705dbdd859b2)
谢~

**Comment by Yu-Fangxu** [comment]
感谢关注！在安装时候可能并不需要特定版本，比如datasets和huggingface-hub只要都有就行，应该跑起来不是很复杂

**Comment by Dengdan-1999** [comment]
好的，非常感谢大佬的解答。佬，我还有一个问题想请教一下你。就是在CLModel类里面为什么self.mask_value = 50265，为什么这里设置为50265呢，词汇表里面<mask>不是50264吗

**Comment by Yu-Fangxu** [comment]
你好，这可能是我当时针对deberta做的修改（有点记不清了），你只需设置成base模型中mask对应的token id即可。
