### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by professional-mix** [Yu-Fangxu/EACL#5]
EACL/lib/python3.10/site-packages/transformers/models/roberta/modeling_roberta.py", line 370, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.
你好运行时遇到了以上的报错，请问您之前有遇到过相似的问题吗？

**Comment by Yu-Fangxu** [comment]
你好，看上去应该是pytorch版本的问题，可以换一下torch版本试试

**Comment by professional-mix** [comment]
感谢大佬，改了下transformers的版本，现在可以了
